import { Fund, Entity, FundStatus, RoadmapStep, DocRequirement } from "./types";

export const ALL_FUNDS: Fund[] = [
  {
    id: "sercotec-abeja-2026",
    name: "SERCOTEC Capital Abeja Emprende 2026",
    entity: Entity.SERCOTEC,
    amount: "$3.500.000 CLP (No reembolsable)",
    amountNumber: 3500000,
    deadline: "27 de Mayo de 2026",
    deadlineISO: "2026-05-27",
    status: FundStatus.TODAY,
    urgency: "CRITICAL",
    category: "Seed",
    description: "Subsidio destinado a nuevos negocios liderados por mujeres que requieran financiamiento para concretar sus proyectos y formalizarse.",
    cofinancing: "80-90% SERCOTEC / 10-20% Aporte de la beneficiaria (puede ser en especie)",
    requirements: [
      "Exclusivo para mujeres (Persona natural de género femenino)",
      "Mayor de 18 años",
      "Sin iniciación de actividades en primera categoría ante el SII al momento de postular",
      "Residir en la región de convocatoria",
      "Completar test de caracterización y formulario de postulación"
    ],
    eligibilityGenderRequired: true,
    eligibilitySalesRestricted: true,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Si hay una mujer en el equipo, postular HOY como titular de la idea.",
    tips: "Completar hoy mismo el formulario rápido de postulación en Sercotec.cl. El fondo cuenta con un presupuesto masivo a nivel nacional.",
    url: "https://www.sercotec.cl/capital-abeja-emprende-2",
    referenceUrlText: "sercotec.cl → Capital Abeja Emprende",
    type: "financiamiento"
  },
  {
    id: "corfo-semilla-inicia-rm-2026",
    name: "CORFO Semilla Inicia RM 2026",
    entity: Entity.CORFO,
    amount: "$15.000.000 CLP ($17.000.000 CLP si es liderado por mujeres)",
    amountNumber: 15000000,
    deadline: "29 de Mayo de 2026 (en 2 días)",
    deadlineISO: "2026-05-29",
    status: FundStatus.THREE_DAYS,
    urgency: "CRITICAL",
    category: "Seed",
    description: "Financiamiento para emprendimientos de alto potencial de crecimiento que estén en fase de idea o prototipo básico, apoyando actividades de validación comercial y prototipado rápido.",
    cofinancing: "85% CORFO / 15% cofinanciamiento beneficiario (puede ser valorizado/especie)",
    requirements: [
      "Persona natural de nacionalidad chilena o extranjera con residencia definitiva",
      "Persona jurídica constituida en Chile con menos de 18 meses de antigüedad y SIN ventas",
      "Proyecto de alto potencial y escalabilidad global"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: true,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Milton no tiene empresa constituida aún y reporta $0 ventas, por lo que aplica perfectamente como Persona Natural.",
    tips: "Preparar el resumen del proyecto TI hoy mismo enfocándose en la diferenciación del software respecto a soluciones genéricas.",
    url: "https://www.corfo.cl",
    referenceUrlText: "corfo.cl → Semilla Inicia RM",
    type: "financiamiento"
  },
  {
    id: "corfo-crea-valida-2026",
    name: "CORFO Crea y Valida 2026",
    entity: Entity.CORFO,
    amount: "$180.000.000 CLP (Hasta $220.000.000 CLP colaborativo)",
    amountNumber: 180000000,
    deadline: "9 de Junio de 2026",
    deadlineISO: "2026-06-09",
    status: FundStatus.UPCOMING,
    urgency: "HIGH",
    category: "R&D",
    description: "Apoya el desarrollo de nuevos productos o procesos que requieran de investigación y desarrollo (I+D) aplicada para su validación comercial.",
    cofinancing: "70% a 80% CORFO según tamaño de empresa / 20% a 30% contraparte",
    requirements: [
      "Personas jurídicas constituidas en Chile (no hay límite de antigüedad)",
      "Personas naturales mayores de 18 años con iniciación de actividades",
      "Proyectos con componente tecnológico de alta complejidad (I+D aplicada)"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: false,
    miltonAplica: "SÍ — Excelente para proyectos de software con innovación dura (IA aplicada, algoritmos de optimización, etc.).",
    tips: "El primer paso consiste en postular un perfil breve de sólo 2 páginas. Es una excelente ventana de oportunidad para validar ideas complejas.",
    url: "https://www.corfo.cl",
    referenceUrlText: "corfo.cl → Crea y Valida (Perfil)",
    type: "financiamiento"
  },
  {
    id: "corfo-semilla-inicia-mujeres-2026",
    name: "CORFO Semilla Inicia Mujeres 2026",
    entity: Entity.CORFO,
    amount: "$17.000.000 CLP (No reembolsable)",
    amountNumber: 17000000,
    deadline: "15 de Junio de 2026",
    deadlineISO: "2026-06-15",
    status: FundStatus.UPCOMING,
    urgency: "HIGH",
    category: "Seed",
    description: "Línea nacional del Semilla Inicia exclusiva para proyectos de alto impacto liderados o co-liderados por mujeres, otorgando un monto de financiamiento superior.",
    cofinancing: "85% CORFO / 15% contraparte",
    requirements: [
      "Emprendimiento liderado por mujeres",
      "Persona natural mujer de 18+ o persona jurídica conformada mayoritariamente por mujeres",
      "Constitución menor a 18 meses con ventas iguales a cero"
    ],
    eligibilityGenderRequired: true,
    eligibilitySalesRestricted: true,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Si Milton incluye una mujer socia como titular o co-titular del proyecto.",
    tips: "Si el equipo de 3 cuenta con una mujer en liderazgo, obtendrán $2.000.000 CLP adicionales respecto al fondo Semilla regular.",
    url: "https://www.corfo.cl",
    referenceUrlText: "corfo.cl → Semilla Inicia Mujeres",
    type: "financiamiento"
  },
  {
    id: "corfo-semilla-expande-mujeres-2026",
    name: "CORFO Semilla Expande Mujeres 2026",
    entity: Entity.CORFO,
    amount: "Hasta $50.000.000 CLP (Fase 1 + opcional Fase 2)",
    amountNumber: 50000000,
    deadline: "16 de Junio de 2026",
    deadlineISO: "2026-06-16",
    status: FundStatus.UPCOMING,
    urgency: "MEDIUM",
    category: "Growth",
    description: "Financiamiento para startups con ventas iniciales o tracción concreta lideradas por mujeres que buscan expandir sus operaciones nacionales e internacionales.",
    cofinancing: "85% CORFO / 15% contraparte",
    requirements: [
      "Persona jurídica < 36 meses constituida liderada por mujeres",
      "Contar con ventas previas facturadas dentro del periodo elegible (mínimo $100.000 CLP en los últimos 12 meses)",
      "Proyecto de alcance global"
    ],
    eligibilityGenderRequired: true,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: true,
    miltonAplica: "NO DIRECTAMENTE — Milton no tiene ventas previas ni empresa constituida.",
    tips: "Postular a Semilla Inicia hoy para validar, y en 12 a 18 meses escalar hacia esta convocación con ventas e historial.",
    url: "https://www.corfo.cl",
    referenceUrlText: "corfo.cl → Semilla Expande Mujeres",
    type: "financiamiento"
  },
  {
    id: "corfo-sumate-innovar-sostenible-2026",
    name: "CORFO Súmate a Innovar Sostenible 2026",
    entity: Entity.CORFO,
    amount: "$10.000.000 CLP (No reembolsable)",
    amountNumber: 10000000,
    deadline: "01 de Julio de 2026",
    deadlineISO: "2026-07-01",
    status: FundStatus.OPEN,
    urgency: "MEDIUM",
    category: "Innovation",
    description: "Financiamiento rápido para resolver desafíos críticos de sostenibilidad, economía circular o eficiencia energética mediante la adaptación de tecnologías e innovaciones.",
    cofinancing: "80% CORFO / 20% contraparte",
    requirements: [
      "Personas jurídicas de cualquier tamaño registradas en Chile",
      "Personas naturales con iniciación de actividades de primera o segunda categoría ante el SII",
      "Enfoque directo en economía circular, eficiencia o impacto ambiental"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: false,
    miltonAplica: "SÍ — Si Milton enmarca el software hacia un impacto sostenible (ej. eficiencia energética, control inteligente de recursos, digitalización o medición de huella).",
    tips: "Desarrollar un pitch que resalte el impacto sostenible u optimización ecológica del sistema SaaS planteado.",
    url: "https://www.corfo.cl",
    referenceUrlText: "corfo.cl → Súmate a Innovar Sostenible",
    type: "financiamiento"
  },
  {
    id: "sercotec-semilla-emprende",
    name: "SERCOTEC Capital Semilla Emprende",
    entity: Entity.SERCOTEC,
    amount: "Hasta $4.500.000 CLP",
    amountNumber: 4500000,
    deadline: "Convocatorias regionales múltiples (Revisar RM)",
    deadlineISO: "2026-06-30",
    status: FundStatus.OPEN,
    urgency: "MEDIUM",
    category: "Seed",
    description: "Financia el plan de trabajo de nuevos emprendedores sin inicio de actividades que deseen formalizarse en el SII e instalar un negocio.",
    cofinancing: "80-90% SERCOTEC / 10-20% Aporte beneficiario",
    requirements: [
      "Personas naturales mayores de 18 años sin iniciación de actividades en primera categoría",
      "Plan de negocio local viable",
      "Tener un aporte pecuniario propio en efectivo"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: true,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Milton no ha iniciado actividades mercantiles y es ideal para constituir su primera SpA del rubro TI.",
    tips: "El proceso es más directo y menos tecnológico que los de CORFO, lo que lo hace muy viable para costear hardware, diseño de marca o servidores iniciales.",
    url: "https://www.sercotec.cl",
    referenceUrlText: "sercotec.cl → Capital Semilla",
    type: "financiamiento"
  },
  {
    id: "sercotec-pioneras-2026",
    name: "SERCOTEC Capital Pioneras 2026",
    entity: Entity.SERCOTEC,
    amount: "Hasta $5.000.000 CLP",
    amountNumber: 5000000,
    deadline: "Por confirmar nacionalmente (Revisar RM)",
    deadlineISO: "2026-06-20",
    status: FundStatus.VERIFY,
    urgency: "HIGH",
    category: "Seed",
    description: "Fondo especial para fomentar el emprendimiento femenino en sectores productivos tradicionalmente masculinos, como lo es la industria tecnológica y de software.",
    cofinancing: "80-90% SERCOTEC / Aporte restante por beneficiaria",
    requirements: [
      "Mujeres con o sin inicio de actividades",
      "Proyecto enmarcado en rubros definidos de baja participación femenina (TI califica perfectamente)",
      "Presentación de video pitch y plan de trabajo simplificado"
    ],
    eligibilityGenderRequired: true,
    eligibilitySalesRestricted: true,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Al ser TI/Software un rubro sumamente masculino, contar con una mujer en el equipo hace que este fondo sea una postulación de altísima probabilidad de éxito.",
    tips: "Excelente diferencial. El fondo tiene un pool de competencia menor comparado con los fondos de fomento general.",
    url: "https://www.sercotec.cl",
    referenceUrlText: "sercotec.cl → Capital Pioneras",
    type: "financiamiento"
  },
  {
    id: "startup-chile-build-big12",
    name: "Startup Chile Build (BIG 12)",
    entity: Entity.STARTUP_CHILE,
    amount: "$15.000.000 CLP (Equity Free / Subsidio completo)",
    amountNumber: 15000000,
    deadline: "Siguiente ronda: Noviembre 2026 (Cerró 25/05)",
    deadlineISO: "2026-11-20",
    status: FundStatus.CLOSED,
    urgency: "CLOSED",
    category: "Seed",
    description: "Acelera ideas de base tecnológica en etapa temprana. Entrega mentorías, workshops, red de inversionistas globales, visas de trabajo y dinero no reembolsable sin tomar acciones de la empresa.",
    cofinancing: "Subsidio de financiamiento libre de capital accionario",
    requirements: [
      "Idea disruptiva de base tecnológica (software, hardware, SaaS)",
      "Equipo fundador calificado (mínimo 1 integrante dedicado al 100%)",
      "Proyecto con ambición e internacionalización"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: true,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Al ser una idea de software TI (pudiendo ser IA o SaaS), califica directamente para la categoría Build.",
    tips: "El 25 de mayo cerró la ronda actual. Comenzar a preparar el deck, pitch y prototipo inicial para la histórica convocaciones de noviembre de 2026.",
    url: "https://www.startupchile.org",
    referenceUrlText: "startupchile.org → Alertas BIG 12",
    type: "financiamiento"
  },
  {
    id: "anid-fondef-idea-2026",
    name: "ANID Fondef IDeA 2026",
    entity: Entity.ANID,
    amount: "Hasta $250.000.000 CLP (Proyectos de I+D)",
    amountNumber: 250000000,
    deadline: "2° Semestre (Agosto - Octubre aprox.)",
    deadlineISO: "2026-09-15",
    status: FundStatus.PENDING_OPENING,
    urgency: "MEDIUM",
    category: "R&D",
    description: "Financia investigación científica y tecnológica aplicada de alto impacto comercial mediante alianzas estratégicas entre investigadores y empresas.",
    cofinancing: "Financia hasta el 70% del costo del proyecto / 30% restante por los asociados",
    requirements: [
      "Alianza obligatoria con Instituciones académicas o centros de investigación",
      "Componente científico-tecnológico sustancial e innovador",
      "Compromiso de transferencia del software o tecnología al sector productivo"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: true,
    miltonAplica: "SÍ — Recomendable para desarrollos de software que requieran validación científica muy alta (ej. big data avanzado, robótica, IA de aprendizaje profundo).",
    tips: "Un camino valioso para Milton es acercarse a un centro de innovación universitario para actuar de co-ejecutor técnico.",
    url: "https://www.anid.cl",
    referenceUrlText: "anid.cl → Fondef IDeA",
    type: "financiamiento"
  },

  {
    id: "startup-chile-ignite-2026",
    name: "Startup Chile Ignite (BIG 12)",
    entity: Entity.STARTUP_CHILE,
    amount: "$30.000.000 CLP (Equity Free / Subsidio completo)",
    amountNumber: 30000000,
    deadline: "Siguiente ronda: Noviembre 2026",
    deadlineISO: "2026-11-20",
    status: FundStatus.PENDING_OPENING,
    urgency: "MEDIUM",
    category: "Growth",
    description: "Acelera startups con MVP funcional en fase de product-market fit. Entrega $30M CLP sin tomar acciones, más mentorías, red de inversionistas globales y visas de trabajo.",
    cofinancing: "Subsidio de financiamiento libre de capital accionario",
    requirements: [
      "Startup tecnológica con MVP validado y primeras ventas o usuarios activos",
      "Equipo con al menos 1 integrante dedicado al 100%",
      "Proyecto con ambición de internacionalización"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Meta para la ronda de noviembre 2026 una vez que Milton tenga un MVP con primeras validaciones de mercado.",
    tips: "Postular primero a Build ($15M). Ignite es el siguiente escalón natural. Preparar métricas de tracción, usuarios activos y feedback validado.",
    url: "https://www.startupchile.org",
    referenceUrlText: "startupchile.org → Alertas BIG 12 Ignite",
    type: "financiamiento"
  },
  {
    id: "startup-chile-growth-2026",
    name: "Startup Chile Growth (BIG 12)",
    entity: Entity.STARTUP_CHILE,
    amount: "$75.000.000 CLP (Equity Free / Subsidio completo)",
    amountNumber: 75000000,
    deadline: "Siguiente ronda: Noviembre 2026",
    deadlineISO: "2026-11-20",
    status: FundStatus.PENDING_OPENING,
    urgency: "LOW",
    category: "Growth",
    description: "Programa de expansión para startups con tracción demostrada que buscan escalar internacionalmente. El mayor subsidio no reembolsable de Startup Chile, sin cesión de equity.",
    cofinancing: "Subsidio de financiamiento libre de capital accionario",
    requirements: [
      "Startup con ingresos recurrentes y métricas de crecimiento documentadas",
      "Empresa constituida con operaciones activas",
      "Plan de expansión internacional validado"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: true,
    miltonAplica: "Meta a 18-24 meses — requiere tracción real (ventas, usuarios, ARR). El camino: Build → Ignite → Growth.",
    tips: "Objetivo de largo plazo. Comenzar con Build en noviembre 2026, acumular métricas de crecimiento, y escalar a Growth en ronda 2027-2028.",
    url: "https://www.startupchile.org",
    referenceUrlText: "startupchile.org → Alertas BIG 12 Growth",
    type: "financiamiento"
  },

  /* --- LICITACIONES — MERCADO PÚBLICO TI (Fuente: todolicitaciones.cl, 26-mayo-2026) --- */
  /* Nota: Estas licitaciones ya cerraron su recepción de ofertas. Se presentan como         */
  /* referencias de mercado verificadas: los organismos vuelven a licitar los mismos          */
  /* servicios cada 12-24 meses. Estudiar sus bases es preparación para la próxima ronda.     */
  {
    id: "lic-isp-sistemas-informaticos",
    name: "Servicios Sistemas Informáticos E1O2RT9 — ISP",
    entity: "Instituto de Salud Pública de Chile",
    amount: "$168.666.667 CLP (~2.508 UTM)",
    amountNumber: 168666667,
    deadline: "CERRADA — 26 de Mayo de 2026",
    deadlineISO: "2026-05-26",
    status: FundStatus.CLOSED,
    urgency: "CLOSED",
    category: "Licitación Pública",
    description: "Servicios de desarrollo, soporte y mantención de sistemas informáticos para la Oficina de Tecnología y Comunicaciones del ISP Chile. Producto UNSPSC: Software de entorno de desarrollo.",
    cofinancing: "Pago contra hitos entregables según contrato marco. Adjudicación estimada julio-agosto 2026.",
    requirements: [
      "Empresa con experiencia previa demostrable en desarrollo y soporte de sistemas informáticos",
      "Inscripción vigente en ChileProveedores",
      "Garantía de seriedad de la oferta según bases técnicas"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: true,
    miltonAplica: "NO inmediatamente — LP grande ($168M) requiere empresa con track record sólido demostrable. Meta a 12-18 meses. El ISP licita sistemas TI frecuentemente: monitorear próximas convocatorias.",
    tips: "Estudiar las bases técnicas de esta licitación para entender los requerimientos del ISP. Alta probabilidad de que vuelvan a licitar en 2027. Con SpA + 1 año de experiencia, Milton podría postular en consorcio.",
    url: "https://www.mercadopublico.cl",
    referenceUrlText: "mercadopublico.cl → Código 813-53-LP26",
    type: "licitacion",
    chileCode: "813-53-LP26",
    organizer: "Instituto de Salud Pública de Chile (ISP)"
  },
  {
    id: "lic-las-condes-participacion-2026",
    name: "Plataforma Web de Participación Ciudadana — Las Condes",
    entity: "Municipalidad de Las Condes",
    amount: "$50.000.000 CLP (~743 UTM) por 24 meses",
    amountNumber: 50000000,
    deadline: "CERRADA — 5 de Mayo de 2026",
    deadlineISO: "2026-05-05",
    status: FundStatus.CLOSED,
    urgency: "CLOSED",
    category: "Licitación Pública",
    description: "Contratación por 24 meses de plataforma web de participación ciudadana en modalidad SaaS para la Municipalidad de Las Condes. Producto UNSPSC: Software de desarrollo de plataforma web.",
    cofinancing: "Contrato SaaS mensual a 30 días. $2.083.333 CLP/mes por 24 meses.",
    requirements: [
      "Empresa jurídica inscrita en ChileProveedores",
      "Plataforma SaaS web con experiencia en participación ciudadana o similar",
      "Soporte técnico y SLA documentado"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: true,
    miltonAplica: "SÍ — Este es exactamente el tipo de proyecto ideal para Milton: SaaS municipal de participación ciudadana. Las Condes, Providencia, Ñuñoa y Vitacura repiten este tipo de licitación regularmente.",
    tips: "Desarrollar ahora un MVP de plataforma de participación ciudadana o consulta vecinal. Las municipalidades grandes RM licitan estos servicios SaaS cada 24 meses. Con SpA + prototipo, postular a la próxima ronda.",
    url: "https://www.mercadopublico.cl",
    referenceUrlText: "mercadopublico.cl → Código 2345-64-LE26",
    type: "licitacion",
    chileCode: "2345-64-LE26",
    organizer: "I. Municipalidad de Las Condes"
  },
  {
    id: "lic-providencia-permisos-bnup",
    name: "Sistema de Otorgamiento de Permisos BNUP — Providencia",
    entity: "Municipalidad de Providencia",
    amount: "$6.700.000 – $67.000.000 CLP (100-1.000 UTM, LE)",
    amountNumber: 20000000,
    deadline: "CERRADA — 6 de Mayo de 2026",
    deadlineISO: "2026-05-06",
    status: FundStatus.CLOSED,
    urgency: "CLOSED",
    category: "Licitación Pública",
    description: "Desarrollo del sistema de otorgamiento de permisos en el Bien Nacional de Uso Público (BNUP) para la Dirección de Infraestructura de la Municipalidad de Providencia. Plataforma web a medida.",
    cofinancing: "Pago contra entrega y aprobación del sistema por la Dirección de Infraestructura.",
    requirements: [
      "Empresa o persona natural con iniciación de actividades SII en rubro TI",
      "Inscripción básica o completa en ChileProveedores",
      "Propuesta técnica con arquitectura del sistema y plazo de entrega"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: false,
    miltonAplica: "SÍ — Formato LE accesible para empresa nueva. Providencia licita desarrollo de sistemas web frecuentemente. Con SII iniciado + ChileProveedores, Milton puede postular a la próxima convocatoria similar.",
    tips: "Monitorear activamente: mercadopublico.cl → filtrar por organismo 'Municipalidad de Providencia' → categoría software. Este tipo de licitaciones LE aparecen cada 3-6 meses.",
    url: "https://www.mercadopublico.cl",
    referenceUrlText: "mercadopublico.cl → Código 2490-34-LE26",
    type: "licitacion",
    chileCode: "2490-34-LE26",
    organizer: "I. Municipalidad de Providencia"
  },
  {
    id: "lic-vitacura-talleres-2026",
    name: "Talleres de Empleabilidad Digital — Vitacura",
    entity: "Municipalidad de Vitacura",
    amount: "≤$6.729.400 CLP (≤100 UTM — Compra Ágil L1)",
    amountNumber: 6729400,
    deadline: "CERRADA — 21 de Abril de 2026",
    deadlineISO: "2026-04-21",
    status: FundStatus.CLOSED,
    urgency: "CLOSED",
    category: "Compra Ágil",
    description: "Contratación de talleres de empleabilidad para vecinos de Vitacura. Categoría UNSPSC: Formación y capacitación de personal + Software plataforma web. Formato L1 (Compra Ágil ≤100 UTM).",
    cofinancing: "Pago directo contra boleta o factura. Compra directa sin proceso licitatorio largo.",
    requirements: [
      "Persona natural o empresa con iniciación de actividades SII",
      "Inscripción básica en ChileProveedores (proceso de 1-3 días)",
      "Cotización en PDF con descripción del taller y plataforma digital incluida"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: false,
    miltonAplica: "SÍ — Formato más accesible del mercado público. Con SII iniciado + ChileProveedores, Milton puede cotizar en menos de 1 semana. Vitacura, Las Condes, Providencia y Ñuñoa licitan talleres de capacitación digital 3-5 veces al año.",
    tips: "Propuesta diferenciadora: taller de empleabilidad digital + plataforma online propia = mayor valor que solo charlas. Ticket pequeño ($6M) pero proceso simple y repetible. Ideal para construir track record en Mercado Público.",
    url: "https://www.mercadopublico.cl",
    referenceUrlText: "mercadopublico.cl → Código 1480209-13-L126",
    type: "licitacion",
    chileCode: "1480209-13-L126",
    organizer: "I. Municipalidad de Vitacura"
  },
  {
    id: "lic-ejercito-plataforma-personal",
    name: "Plataforma Digital Administración de Personal — Ejército",
    entity: "División Logística del Ejército de Chile",
    amount: "$440.300.000 CLP (~6.546 UTM — LR)",
    amountNumber: 440300000,
    deadline: "CERRADA — 14 de Mayo de 2026",
    deadlineISO: "2026-05-14",
    status: FundStatus.CLOSED,
    urgency: "CLOSED",
    category: "Licitación Grande",
    description: "Adquisición e implementación de sistema que reemplace el SIAP (Sistema de Administración de Personal) del Ejército de Chile. Transformación de datos + plataforma web para gestión de RRHH institucional.",
    cofinancing: "Contrato de implementación y soporte plurianual. Pago contra hitos de entrega y pruebas de aceptación.",
    requirements: [
      "Empresa con experiencia en sistemas ERP o HCM institucionales de gran escala",
      "Track record demostrable con organismos del Estado de Chile",
      "Garantías bancarias de fiel cumplimiento según bases técnicas"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: true,
    miltonAplica: "NO inmediatamente — LR grande ($440M) requiere empresa establecida con historial institucional. Referencia útil para entender el mercado de sistemas ERP para FFAA. Estrategia: subcontratar como partner tecnológico de una empresa grande en 2-3 años.",
    tips: "Estudiar este pliego como referencia del mercado institucional. Los sistemas de RRHH para FFAA y ministerios se renuevan cada 5-8 años. Monitorear licitaciones similares de menor escala en otros organismos (servicios públicos, municipalidades).",
    url: "https://www.mercadopublico.cl",
    referenceUrlText: "mercadopublico.cl → Código 647431-4-LR26",
    type: "licitacion",
    chileCode: "647431-4-LR26",
    organizer: "División Logística del Ejército de Chile"
  },

  /* --- HACKATONES & COMPETENCIAS TECH (Fuente: docs/Hackathones_AI_Chile_2026_v2.docx) --- */
  {
    id: "hack-academia-hacklab-2026",
    name: "AcademIA HackLab 2026",
    entity: "Ciudad Emergente",
    amount: "Premios por confirmar + Créditos Google Cloud",
    amountNumber: 0,
    deadline: "1 de Julio al 5 de Agosto de 2026",
    deadlineISO: "2026-07-01",
    status: FundStatus.OPEN,
    urgency: "HIGH",
    category: "Hackathon IA",
    description: "Hackathon presencial en Santiago para desarrollar soluciones de IA aplicada a la transformación urbana. Organizado por Ciudad Emergente, Google, CORFO y MinCiencia. Edición 2025 contó con apoyo de Google y CORFO.",
    cofinancing: "Sin costo de inscripción. Créditos Google Cloud para equipos participantes. Networking con Google Chile.",
    requirements: [
      "Profesionales, emprendedores o estudiantes mayores de 18 años",
      "Equipos de 2 a 5 personas (individuales pueden sumarse a equipos)",
      "Propuesta de solución IA aplicada a problemática urbana (movilidad, medioambiente, seguridad, participación ciudadana)"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Formato ideal: equipo pequeño + IA aplicada a problemática urbana. Google Chile presente como organizador directo. Sin empresa requerida, sin restricción de ventas.",
    tips: "Inscripciones abiertas AHORA en ciudademergente.org/postula. Ubicación: Puma 1180, Recoleta, Santiago. Preparar propuesta de app urbana con IA generativa. El networking con Google Chile y CORFO es el premio real.",
    url: "https://ciudademergente.org/academia-hacklab",
    referenceUrlText: "ciudademergente.org → AcademIA HackLab 2026",
    type: "hackaton",
    chileCode: "ACADEMIA-HACKLAB-2026",
    organizer: "Ciudad Emergente + Google + CORFO + MinCiencia"
  },
  {
    id: "hack-oqi-latam-2026",
    name: "OQI Hackathon LATAM 2026",
    entity: "OQI / BUAP",
    amount: "Premios por confirmar",
    amountNumber: 0,
    deadline: "29 de Junio al 1 de Julio de 2026",
    deadlineISO: "2026-06-29",
    status: FundStatus.UPCOMING,
    urgency: "HIGH",
    category: "Hackathon LATAM",
    description: "Hackathon virtual LATAM organizado por OQI (BUAP, México). Modalidad híbrida con base en Puebla, México y participación remota disponible para Chile. Foco en tecnología e innovación para LATAM.",
    cofinancing: "Participación gratuita. Premios por confirmar para edición 2026.",
    requirements: [
      "Equipos de 2 a 5 personas de cualquier país de LATAM",
      "Participación remota disponible para Chile (no requiere desplazarse a México)",
      "Propuesta de solución tecnológica para problemática latinoamericana"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — 100% virtual desde Chile. Sin empresa requerida. Oportunidad de exposición en red LATAM. Participar antes del AcademIA HackLab para practicar pitch y prototipado.",
    tips: "Buscar convocatoria oficial en redes: 'OQI Hackathon LATAM 2026'. Participación gratuita y 100% remota desde Santiago. Buen warmup antes de los hackathones presenciales.",
    url: "https://www.mercadopublico.cl",
    referenceUrlText: "Buscar: OQI Hackathon LATAM 2026 en redes sociales",
    type: "hackaton",
    chileCode: "OQI-LATAM-2026",
    organizer: "OQI / Universidad Autónoma de Puebla (BUAP)"
  },
  {
    id: "hack-ia-challenge-latam-2026",
    name: "IA Challenge LATAM — Desafío Latam + Oracle",
    entity: "Desafío Latam",
    amount: "USD $1.000 total (1°: $750 + 2°: $250) + 300 créditos Oracle Cloud",
    amountNumber: 1000000,
    deadline: "Inscripciones estimadas: Julio 2026 (edición 2026 por anunciar)",
    deadlineISO: "2026-07-15",
    status: FundStatus.PENDING_OPENING,
    urgency: "MEDIUM",
    category: "Hackathon IA",
    description: "Competencia virtual LATAM organizada por Desafío Latam y Oracle Academy. Temáticas 2025: Bienestar Humano & Salud Global / Educación y Futuro del Trabajo. Todos los equipos reciben 300 créditos Oracle Cloud gratuitos.",
    cofinancing: "Participación gratuita + 300 créditos Oracle Cloud para todos los participantes (~USD 300 en infraestructura). Premio en efectivo para top 2.",
    requirements: [
      "Mayores de 18 años (equipos de 3 a 5 personas recomendado)",
      "Chile elegible — 100% virtual, participación remota",
      "Uso de Oracle Cloud en la solución (créditos gratis entregados al inscribirse)"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — 100% virtual LATAM, Chile elegible, equipo de 2-3 personas aplica. Créditos Oracle Cloud gratis equivalen a infraestructura para alojar el MVP inicial durante meses.",
    tips: "Activar alerta en desafiolatam.com para la edición 2026. Inscripciones típicamente julio, build agosto, final agosto. Certificación Oracle gratuita para todos los participantes independiente del resultado.",
    url: "https://desafiolatam.com/hackathon-2026",
    referenceUrlText: "desafiolatam.com → IA Challenge LATAM 2026",
    type: "hackaton",
    chileCode: "IA-CHALLENGE-LATAM-2026",
    organizer: "Desafío Latam + Oracle Academy + NTT Data"
  },
  {
    id: "hack-worlds-largest-2026",
    name: "World's Largest Hackathon (Bolt.new) — Edición 2026",
    entity: "StackBlitz / Devpost",
    amount: "USD $1.000.000+ total | 1° lugar: USD $100.000",
    amountNumber: 100000000,
    deadline: "Edición 2026 por anunciar (2025 fue: 30 mayo – 30 junio)",
    deadlineISO: "2026-06-30",
    status: FundStatus.PENDING_OPENING,
    urgency: "MEDIUM",
    category: "Hackathon Global",
    description: "El hackathon virtual más grande del mundo, organizado por StackBlitz (Bolt.new) y Devpost. Edición 2025: 30 mayo al 30 junio 2025. Premio total $1M+ USD. Requiere construir una app con Bolt.new (IA generativa full-stack). Chile elegible.",
    cofinancing: "Participación gratuita. $1M+ USD en premios distribuidos en múltiples categorías. AWS y otros sponsors entregan créditos cloud adicionales.",
    requirements: [
      "Mayores de 18 años — Chile elegible ✅",
      "App construida con Bolt.new (generador de apps con IA generativa de StackBlitz)",
      "Proyecto publicado en Devpost antes del cierre de la edición 2026"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — 100% virtual, Chile elegible, sin empresa requerida. Bolt.new permite crear apps full-stack en horas con IA generativa. El premio de $100.000 USD (1°) equivale a ~$100M CLP.",
    tips: "Activar alerta en bolt.new/blog para la convocatoria 2026. Practicar con Bolt.new ahora: construir el MVP del producto en Bolt.new es preparación simultánea para el hackathon y para el pitch de inversión.",
    url: "https://bolt.new",
    referenceUrlText: "bolt.new → Activar alerta hackathon 2026",
    type: "hackaton",
    chileCode: "WORLDS-LARGEST-2026",
    organizer: "StackBlitz (Bolt.new) + Devpost"
  },
  {
    id: "hack-built-with-claude-2026",
    name: "Built with Claude — Anthropic + Cerebral Valley",
    entity: "Anthropic",
    amount: "Créditos API Claude + premios en efectivo (varía por edición)",
    amountNumber: 300000,
    deadline: "Múltiples ediciones durante 2026 (por anunciar)",
    deadlineISO: "2026-12-31",
    status: FundStatus.RECURRENT,
    urgency: "LOW",
    category: "Hackathon IA",
    description: "Hackathon virtual organizado por Anthropic y Cerebral Valley. Múltiples ediciones durante el año. Requiere usar Claude API o Claude Code en el proyecto. Chile elegible. Créditos API Claude entregados a participantes.",
    cofinancing: "Participación gratuita. Créditos API Claude para todos los equipos. Premios en efectivo y acceso anticipado a nuevos modelos.",
    requirements: [
      "Mayores de 18 años — Chile elegible ✅",
      "Proyecto que use Claude API o Claude Code como componente central",
      "Demo funcional publicada antes del cierre de cada edición"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Si el proyecto de Milton usa IA (muy probable en SaaS TI), integrar Claude API es natural. Múltiples ediciones = múltiples oportunidades durante el año.",
    tips: "Revisar anthropic.com/events y cerebralvalley.ai para próximas fechas. La comunidad de Anthropic tiene acceso anticipado a nuevos modelos, lo cual es un activo estratégico más allá del premio.",
    url: "https://anthropic.com/events",
    referenceUrlText: "anthropic.com/events → Built with Claude",
    type: "hackaton",
    chileCode: "BUILT-WITH-CLAUDE-2026",
    organizer: "Anthropic + Cerebral Valley"
  },
  {
    id: "hack-openai-chile-2026",
    name: "OpenAI Hackathon Chile & LATAM",
    entity: "OpenAI",
    amount: "Créditos API GPT-4 + premios en efectivo (varía por edición)",
    amountNumber: 500000,
    deadline: "Múltiples ediciones durante 2026 — primera hackathon OpenAI en Chile",
    deadlineISO: "2026-12-31",
    status: FundStatus.RECURRENT,
    urgency: "LOW",
    category: "Hackathon IA",
    description: "Primera hackathon oficial de OpenAI en Chile y LATAM, organizada junto con Comunidad IA Chile. Modalidad virtual/híbrida. Comunidad activa en Santiago. Requiere app construida con GPT-4, DALL-E, Whisper u otras APIs de OpenAI.",
    cofinancing: "Participación gratuita. Créditos OpenAI API para participantes. Premios en efectivo por categoría.",
    requirements: [
      "Mayores de 18 años — Chile elegible ✅",
      "App o servicio construido con APIs de OpenAI (GPT-4, DALL-E, Whisper, etc.)",
      "Demo presentada antes del cierre de la edición"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Si el proyecto usa IA generativa (GPT-4 o Whisper), participar es natural. La comunidad IA Chile en Santiago es networking valioso para conseguir primeros clientes o co-fundadores.",
    tips: "Revisar openai.com/events y comunidadIAchile.cl. La red de Comunidad IA Chile organiza meetups mensuales en Santiago — asistir antes del hackathon para hacer equipo con otros desarrolladores.",
    url: "https://openai.com/events",
    referenceUrlText: "openai.com/events → Hackathon Chile LATAM",
    type: "hackaton",
    chileCode: "OPENAI-CHILE-2026",
    organizer: "OpenAI + Comunidad IA Chile"
  },
  {
    id: "hack-nasa-space-apps-2026",
    name: "NASA Space Apps Challenge 2026",
    entity: "NASA",
    amount: "Reconocimiento global + viaje a instalaciones NASA (ganadores globales)",
    amountNumber: 0,
    deadline: "~Octubre 2026 (edición 2025: 4-6 octubre)",
    deadlineISO: "2026-10-04",
    status: FundStatus.PENDING_OPENING,
    urgency: "MEDIUM",
    category: "Hackathon Global",
    description: "El mayor hackathon de ciencia y tecnología del mundo, organizado por NASA con nodos locales en todo el planeta. Nodo activo en Santiago cada año. Desafíos usando datos abiertos de NASA. Virtual y presencial en Santiago.",
    cofinancing: "Participación gratuita. Premio global: viaje a instalaciones de la NASA (EE.UU.) para equipos ganadores.",
    requirements: [
      "Mayores de 18 años — nodo Santiago activo cada octubre ✅",
      "Propuesta de solución a desafíos usando datos abiertos de NASA",
      "Proyecto presentado en spaceapps.nasa.gov"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — El nodo Santiago organiza cada octubre. Sin empresa requerida. Aunque el foco es espacial, hay desafíos de IA aplicada, datos y plataformas que se alinean con proyectos TI. El reconocimiento global es un activo para el perfil del equipo.",
    tips: "Registrarse en spaceapps.nasa.gov para alertas de la edición 2026. El nodo Santiago es presencial: buscar en redes 'NASA Space Apps Santiago 2026'. Participar más por el networking y exposición que por el premio monetario.",
    url: "https://spaceapps.nasa.gov",
    referenceUrlText: "spaceapps.nasa.gov → Nodo Santiago",
    type: "hackaton",
    chileCode: "NASA-SPACE-APPS-2026",
    organizer: "NASA + Comunidad local Santiago"
  }
];

export const ROADMAP_STEPS: RoadmapStep[] = [
  {
    id: "step-1",
    timeframe: "ESTA_SEMANA",
    dateText: "HOY - 27 de Mayo 2026",
    title: "Postulación Express Capital Abeja",
    desc: "Si hay mujer empresaria/socia en tu equipo, presentarse HOY mismo en Sercotec.cl para realizar la postulación en línea. Cierra de forma inminente.",
    isUrgent: true,
    color: "from-red-500/30 to-red-600/10 border-red-500/50"
  },
  {
    id: "step-2",
    timeframe: "ESTA_SEMANA",
    dateText: "27-28 de Mayo 2026",
    title: "Redacción del Pitch y Formulario",
    desc: "Ingresar a Corfo.cl y activar el borrador de postulación del 'Semilla Inicia Región Metropolitana'. Detallar el problema de mercado, la solución TI, y el componente de alto potencial.",
    isUrgent: true,
    color: "from-orange-500/30 to-orange-600/10 border-orange-500/50"
  },
  {
    id: "step-3",
    timeframe: "ESTA_SEMANA",
    dateText: "29 de Mayo 2026 (17:00 Hrs)",
    title: "Envío CORFO Semilla Inicia RM",
    desc: "Revisión definitiva y firma digital del borrador. Enviar obligatoriamente antes de la hora límite para evitar saturación de servidores gubernamentales.",
    isUrgent: true,
    color: "from-red-500/40 to-red-500/10 border-red-500/80 shadow-[0_0_15px_rgba(239,68,68,0.25)]"
  },
  {
    id: "step-4",
    timeframe: "JUNIO_2026",
    dateText: "1 al 9 de Junio 2026",
    title: "Enviar Perfil Crea y Valida (I+D)",
    desc: "Redacción del formulario sintético de perfil para proyecto tecnológico aplicado con componente innovador de software.",
    isUrgent: false,
    color: "from-amber-500/20 to-amber-600/5 border-amber-500/30"
  },
  {
    id: "step-5",
    timeframe: "JUNIO_2026",
    dateText: "10 de Junio 2026",
    title: "Constitución Express de SpA",
    desc: "Formalizar la startup mediante el portal estatal Tu Empresa En Un Día (registros.cl) de forma 100% o costo marginal, asignando capital inicial desde $1 CLP.",
    isUrgent: false,
    color: "from-blue-500/20 to-blue-600/5 border-blue-500/30"
  },
  {
    id: "step-6",
    timeframe: "JUNIO_2026",
    dateText: "15 de Junio 2026",
    title: "Padrón del Estado & Proveedores",
    desc: "Asociar la SpA en ChileProveedores y activar visibilidad en Mercado Público para disputar licitaciones del rubro de consultoría digital o desarrollo de software.",
    isUrgent: false,
    color: "from-blue-500/20 to-blue-600/5 border-blue-500/30"
  },
  {
    id: "step-7",
    timeframe: "JULIO_AGOSTO_2026",
    dateText: "1 de Julio 2026",
    title: "Postulación Súmate a Innovar Sostenible",
    desc: "Si el modelo de negocio cuenta con un ángulo de monitoreo energético u optimización ambiental de software, postular al fondo de fomento ecológico de CORFO.",
    isUrgent: false,
    color: "from-emerald-500/20 to-emerald-600/5 border-emerald-500/30"
  },
  {
    id: "step-8",
    timeframe: "JULIO_AGOSTO_2026",
    dateText: "Julio 2026",
    title: "Primera Licitación Compra Ágil",
    desc: "Monitorear en Mercado Público compras ágiles menores a 100 UTM para adjudicar los primeros contratos estatales como consultor SpA de informática.",
    isUrgent: false,
    color: "from-yellow-500/20 to-yellow-600/5 border-yellow-500/30"
  },
  {
    id: "step-9",
    timeframe: "JULIO_AGOSTO_2026",
    dateText: "1 Jul - 5 Ago 2026",
    title: "AcademIA HackLab 2026",
    desc: "Participar de la convocatoria de Ciudad Emergente y Google para acelerar el uso de Inteligencia Artificial aplicada en sistemas urbanos y ecológicos.",
    isUrgent: false,
    color: "from-indigo-500/20 to-indigo-600/5 border-indigo-500/30"
  },
  {
    id: "step-10",
    timeframe: "NOVIEMBRE_2026",
    dateText: "Noviembre 2026",
    title: "Postulación Startup Chile BIG 12",
    desc: "Postular a la segunda gran ronda internacional en categorías Build ($15M CLP) para ideas o Ignite ($30M CLP) con el producto SaaS en validación inicial.",
    isUrgent: false,
    color: "from-violet-500/30 to-violet-600/5 border-violet-500/45"
  }
];

export const DOCUMENT_REQUIREMENTS: DocRequirement[] = [
  {
    id: "doc-rut",
    title: "Cédula de Identidad Vigente (RUT)",
    desc: "Cédula chilena del titular del proyecto. Clave Única activa de manera obligatoria.",
    isSpecialForkForSpA: false
  },
  {
    id: "doc-sii",
    title: "Iniciación de Actividades en el SII",
    desc: "Si postulas como personal natural, se tramita de forma inmediata y digital en 1 día hábil vía Sii.cl.",
    isSpecialForkForSpA: false
  },
  {
    id: "doc-pitch",
    title: "Descripción del Proyecto TI (Pitch 2 Pág.)",
    desc: "Formulación del Pain/Problem, la solución tecnológica, el diferencial comercial de SaaS/IA, y tamaño de mercado.",
    isSpecialForkForSpA: false
  },
  {
    id: "doc-equipo",
    title: "Resumen de Currículum e Integrantes",
    desc: "Datos, RUTs, porcentaje de participación futura, y antecedentes de experiencia TI del equipo de 2-3 personas.",
    isSpecialForkForSpA: false
  },
  {
    id: "doc-budget",
    title: "Presupuesto Simplificado de 6 Meses",
    desc: "Planificación de fondos para el costeo de hosting, desarrollo, licencias de IA, activos y publicidad.",
    isSpecialForkForSpA: false
  },
  {
    id: "doc-woman",
    title: "Cédula de la Socia Fundadora (Si aplica)",
    desc: "RUT y certificado de nacimiento/vigencia de la mujer que lidera para validar acceso a los fondos con enfoque de género.",
    isSpecialForkForSpA: false
  },
  {
    id: "doc-spa-const",
    title: "Constitución en portalregistros.cl",
    desc: "Firma digital y registro del acta de la SpA. Idealmente capital inicial desde $1 CLP para formalización rápida.",
    isSpecialForkForSpA: true
  },
  {
    id: "doc-chileprov",
    title: "Inscripción en ChileProveedores",
    desc: "Imprescindible para licitaciones públicas y compras ágiles nacionales en Mercado Público.",
    isSpecialForkForSpA: true
  },
  {
    id: "doc-cert-vigency",
    title: "Certificado de Vigencia de la Sociedad",
    desc: "Documento emitido por el Conservador o el Registro de Empresas y Sociedades que acredita legalidad actual.",
    isSpecialForkForSpA: true
  }
];

export const STRATEGIC_LINKS = [
  {
    id: "l1",
    title: "CORFO",
    desc: "Portal central de fomento productivo de Chile. Aquí se gestionan los fondos Semilla Inicia y Crea y Valida.",
    url: "https://www.corfo.cl",
    action: "Semilla Inicia RM 2026"
  },
  {
    id: "l2",
    title: "SERCOTEC",
    desc: "Servicio de Cooperación Técnica. Gestiona el Capital Abeja (cierra hoy 27-05) y Capital Semilla tradicional.",
    url: "https://www.sercotec.cl",
    action: "Capital Abeja Postular HOY"
  },
  {
    id: "l3",
    title: "Startup Chile",
    desc: "La aceleradora pública número 1 de Latinoamérica. Revisa bases para programas Build ($15M) e Ignite ($30M).",
    url: "https://www.startupchile.org",
    action: "Boletín Alertas Noviembre"
  },
  {
    id: "l4",
    title: "Tu Empresa En Un Día",
    desc: "Constituye tu Sociedad por Acciones (SpA) sin intermediarios legales costosos, de forma express.",
    url: "https://www.registrodeempresasysociedades.cl",
    action: "Crear SpA Express"
  },
  {
    id: "l5",
    title: "Mercado Público",
    desc: "Mercado estatal de transacciones de Chile. Acceso a miles de licitaciones públicas y compras ágiles.",
    url: "https://www.mercadopublico.cl",
    action: "Buscar Licitaciones TI"
  }
];
