import { Fund, Entity, FundStatus, RoadmapStep, DocRequirement } from "./types";

export const ALL_FUNDS: Fund[] = [
  {
    id: "sercotec-abeja-2026",
    name: "SERCOTEC Capital Abeja Emprende 2026",
    entity: Entity.SERCOTEC,
    amount: "$3.500.000 CLP (No reembolsable)",
    amountNumber: 3500000,
    deadline: "27 de Mayo de 2026",
    deadlineISO: "2026-05-27",
    status: FundStatus.TODAY,
    urgency: "CRITICAL",
    category: "Seed",
    description: "Subsidio destinado a nuevos negocios liderados por mujeres que requieran financiamiento para concretar sus proyectos y formalizarse.",
    cofinancing: "80-90% SERCOTEC / 10-20% Aporte de la beneficiaria (puede ser en especie)",
    requirements: [
      "Exclusivo para mujeres (Persona natural de género femenino)",
      "Mayor de 18 años",
      "Sin iniciación de actividades en primera categoría ante el SII al momento de postular",
      "Residir en la región de convocatoria",
      "Completar test de caracterización y formulario de postulación"
    ],
    eligibilityGenderRequired: true,
    eligibilitySalesRestricted: true,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Si hay una mujer en el equipo, postular HOY como titular de la idea.",
    tips: "Completar hoy mismo el formulario rápido de postulación en Sercotec.cl. El fondo cuenta con un presupuesto masivo a nivel nacional.",
    url: "https://www.sercotec.cl/capital-abeja-emprende-2",
    referenceUrlText: "sercotec.cl → Capital Abeja Emprende",
    type: "financiamiento"
  },
  {
    id: "corfo-semilla-inicia-rm-2026",
    name: "CORFO Semilla Inicia RM 2026",
    entity: Entity.CORFO,
    amount: "$15.000.000 CLP ($17.000.000 CLP si es liderado por mujeres)",
    amountNumber: 15000000,
    deadline: "29 de Mayo de 2026 (en 2 días)",
    deadlineISO: "2026-05-29",
    status: FundStatus.THREE_DAYS,
    urgency: "CRITICAL",
    category: "Seed",
    description: "Financiamiento para emprendimientos de alto potencial de crecimiento que estén en fase de idea o prototipo básico, apoyando actividades de validación comercial y prototipado rápido.",
    cofinancing: "85% CORFO / 15% cofinanciamiento beneficiario (puede ser valorizado/especie)",
    requirements: [
      "Persona natural de nacionalidad chilena o extranjera con residencia definitiva",
      "Persona jurídica constituida en Chile con menos de 18 meses de antigüedad y SIN ventas",
      "Proyecto de alto potencial y escalabilidad global"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: true,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Milton no tiene empresa constituida aún y reporta $0 ventas, por lo que aplica perfectamente como Persona Natural.",
    tips: "Preparar el resumen del proyecto TI hoy mismo enfocándose en la diferenciación del software respecto a soluciones genéricas.",
    url: "https://www.corfo.cl",
    referenceUrlText: "corfo.cl → Semilla Inicia RM",
    type: "financiamiento"
  },
  {
    id: "corfo-crea-valida-2026",
    name: "CORFO Crea y Valida 2026",
    entity: Entity.CORFO,
    amount: "$180.000.000 CLP (Hasta $220.000.000 CLP colaborativo)",
    amountNumber: 180000000,
    deadline: "9 de Junio de 2026",
    deadlineISO: "2026-06-09",
    status: FundStatus.UPCOMING,
    urgency: "HIGH",
    category: "R&D",
    description: "Apoya el desarrollo de nuevos productos o procesos que requieran de investigación y desarrollo (I+D) aplicada para su validación comercial.",
    cofinancing: "70% a 80% CORFO según tamaño de empresa / 20% a 30% contraparte",
    requirements: [
      "Personas jurídicas constituidas en Chile (no hay límite de antigüedad)",
      "Personas naturales mayores de 18 años con iniciación de actividades",
      "Proyectos con componente tecnológico de alta complejidad (I+D aplicada)"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: false,
    miltonAplica: "SÍ — Excelente para proyectos de software con innovación dura (IA aplicada, algoritmos de optimización, etc.).",
    tips: "El primer paso consiste en postular un perfil breve de sólo 2 páginas. Es una excelente ventana de oportunidad para validar ideas complejas.",
    url: "https://www.corfo.cl",
    referenceUrlText: "corfo.cl → Crea y Valida (Perfil)",
    type: "financiamiento"
  },
  {
    id: "corfo-semilla-inicia-mujeres-2026",
    name: "CORFO Semilla Inicia Mujeres 2026",
    entity: Entity.CORFO,
    amount: "$17.000.000 CLP (No reembolsable)",
    amountNumber: 17000000,
    deadline: "15 de Junio de 2026",
    deadlineISO: "2026-06-15",
    status: FundStatus.UPCOMING,
    urgency: "HIGH",
    category: "Seed",
    description: "Línea nacional del Semilla Inicia exclusiva para proyectos de alto impacto liderados o co-liderados por mujeres, otorgando un monto de financiamiento superior.",
    cofinancing: "85% CORFO / 15% contraparte",
    requirements: [
      "Emprendimiento liderado por mujeres",
      "Persona natural mujer de 18+ o persona jurídica conformada mayoritariamente por mujeres",
      "Constitución menor a 18 meses con ventas iguales a cero"
    ],
    eligibilityGenderRequired: true,
    eligibilitySalesRestricted: true,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Si Milton incluye una mujer socia como titular o co-titular del proyecto.",
    tips: "Si el equipo de 3 cuenta con una mujer en liderazgo, obtendrán $2.000.000 CLP adicionales respecto al fondo Semilla regular.",
    url: "https://www.corfo.cl",
    referenceUrlText: "corfo.cl → Semilla Inicia Mujeres",
    type: "financiamiento"
  },
  {
    id: "corfo-semilla-expande-mujeres-2026",
    name: "CORFO Semilla Expande Mujeres 2026",
    entity: Entity.CORFO,
    amount: "Hasta $50.000.000 CLP (Fase 1 + opcional Fase 2)",
    amountNumber: 50000000,
    deadline: "16 de Junio de 2026",
    deadlineISO: "2026-06-16",
    status: FundStatus.UPCOMING,
    urgency: "MEDIUM",
    category: "Growth",
    description: "Financiamiento para startups con ventas iniciales o tracción concreta lideradas por mujeres que buscan expandir sus operaciones nacionales e internacionales.",
    cofinancing: "85% CORFO / 15% contraparte",
    requirements: [
      "Persona jurídica < 36 meses constituida liderada por mujeres",
      "Contar con ventas previas facturadas dentro del periodo elegible (mínimo $100.000 CLP en los últimos 12 meses)",
      "Proyecto de alcance global"
    ],
    eligibilityGenderRequired: true,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: true,
    miltonAplica: "NO DIRECTAMENTE — Milton no tiene ventas previas ni empresa constituida.",
    tips: "Postular a Semilla Inicia hoy para validar, y en 12 a 18 meses escalar hacia esta convocación con ventas e historial.",
    url: "https://www.corfo.cl",
    referenceUrlText: "corfo.cl → Semilla Expande Mujeres",
    type: "financiamiento"
  },
  {
    id: "corfo-sumate-innovar-sostenible-2026",
    name: "CORFO Súmate a Innovar Sostenible 2026",
    entity: Entity.CORFO,
    amount: "$10.000.000 CLP (No reembolsable)",
    amountNumber: 10000000,
    deadline: "01 de Julio de 2026",
    deadlineISO: "2026-07-01",
    status: FundStatus.OPEN,
    urgency: "MEDIUM",
    category: "Innovation",
    description: "Financiamiento rápido para resolver desafíos críticos de sostenibilidad, economía circular o eficiencia energética mediante la adaptación de tecnologías e innovaciones.",
    cofinancing: "80% CORFO / 20% contraparte",
    requirements: [
      "Personas jurídicas de cualquier tamaño registradas en Chile",
      "Personas naturales con iniciación de actividades de primera o segunda categoría ante el SII",
      "Enfoque directo en economía circular, eficiencia o impacto ambiental"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: false,
    miltonAplica: "SÍ — Si Milton enmarca el software hacia un impacto sostenible (ej. eficiencia energética, control inteligente de recursos, digitalización o medición de huella).",
    tips: "Desarrollar un pitch que resalte el impacto sostenible u optimización ecológica del sistema SaaS planteado.",
    url: "https://www.corfo.cl",
    referenceUrlText: "corfo.cl → Súmate a Innovar Sostenible",
    type: "financiamiento"
  },
  {
    id: "sercotec-semilla-emprende",
    name: "SERCOTEC Capital Semilla Emprende",
    entity: Entity.SERCOTEC,
    amount: "Hasta $4.500.000 CLP",
    amountNumber: 4500000,
    deadline: "Convocatorias regionales múltiples (Revisar RM)",
    deadlineISO: "2026-06-30",
    status: FundStatus.OPEN,
    urgency: "MEDIUM",
    category: "Seed",
    description: "Financia el plan de trabajo de nuevos emprendedores sin inicio de actividades que deseen formalizarse en el SII e instalar un negocio.",
    cofinancing: "80-90% SERCOTEC / 10-20% Aporte beneficiario",
    requirements: [
      "Personas naturales mayores de 18 años sin iniciación de actividades en primera categoría",
      "Plan de negocio local viable",
      "Tener un aporte pecuniario propio en efectivo"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: true,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Milton no ha iniciado actividades mercantiles y es ideal para constituir su primera SpA del rubro TI.",
    tips: "El proceso es más directo y menos tecnológico que los de CORFO, lo que lo hace muy viable para costear hardware, diseño de marca o servidores iniciales.",
    url: "https://www.sercotec.cl",
    referenceUrlText: "sercotec.cl → Capital Semilla",
    type: "financiamiento"
  },
  {
    id: "sercotec-pioneras-2026",
    name: "SERCOTEC Capital Pioneras 2026",
    entity: Entity.SERCOTEC,
    amount: "Hasta $5.000.000 CLP",
    amountNumber: 5000000,
    deadline: "Por confirmar nacionalmente (Revisar RM)",
    deadlineISO: "2026-06-20",
    status: FundStatus.VERIFY,
    urgency: "HIGH",
    category: "Seed",
    description: "Fondo especial para fomentar el emprendimiento femenino en sectores productivos tradicionalmente masculinos, como lo es la industria tecnológica y de software.",
    cofinancing: "80-90% SERCOTEC / Aporte restante por beneficiaria",
    requirements: [
      "Mujeres con o sin inicio de actividades",
      "Proyecto enmarcado en rubros definidos de baja participación femenina (TI califica perfectamente)",
      "Presentación de video pitch y plan de trabajo simplificado"
    ],
    eligibilityGenderRequired: true,
    eligibilitySalesRestricted: true,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Al ser TI/Software un rubro sumamente masculino, contar con una mujer en el equipo hace que este fondo sea una postulación de altísima probabilidad de éxito.",
    tips: "Excelente diferencial. El fondo tiene un pool de competencia menor comparado con los fondos de fomento general.",
    url: "https://www.sercotec.cl",
    referenceUrlText: "sercotec.cl → Capital Pioneras",
    type: "financiamiento"
  },
  {
    id: "startup-chile-build-big12",
    name: "Startup Chile Build (BIG 12)",
    entity: Entity.STARTUP_CHILE,
    amount: "$15.000.000 CLP (Equity Free / Subsidio completo)",
    amountNumber: 15000000,
    deadline: "Siguiente ronda: Noviembre 2026 (Cerró 25/05)",
    deadlineISO: "2026-11-20",
    status: FundStatus.CLOSED,
    urgency: "CLOSED",
    category: "Seed",
    description: "Acelera ideas de base tecnológica en etapa temprana. Entrega mentorías, workshops, red de inversionistas globales, visas de trabajo y dinero no reembolsable sin tomar acciones de la empresa.",
    cofinancing: "Subsidio de financiamiento libre de capital accionario",
    requirements: [
      "Idea disruptiva de base tecnológica (software, hardware, SaaS)",
      "Equipo fundador calificado (mínimo 1 integrante dedicado al 100%)",
      "Proyecto con ambición e internacionalización"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: true,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Al ser una idea de software TI (pudiendo ser IA o SaaS), califica directamente para la categoría Build.",
    tips: "El 25 de mayo cerró la ronda actual. Comenzar a preparar el deck, pitch y prototipo inicial para la histórica convocaciones de noviembre de 2026.",
    url: "https://www.startupchile.org",
    referenceUrlText: "startupchile.org → Alertas BIG 12",
    type: "financiamiento"
  },
  {
    id: "anid-fondef-idea-2026",
    name: "ANID Fondef IDeA 2026",
    entity: Entity.ANID,
    amount: "Hasta $250.000.000 CLP (Proyectos de I+D)",
    amountNumber: 250000000,
    deadline: "2° Semestre (Agosto - Octubre aprox.)",
    deadlineISO: "2026-09-15",
    status: FundStatus.PENDING_OPENING,
    urgency: "MEDIUM",
    category: "R&D",
    description: "Financia investigación científica y tecnológica aplicada de alto impacto comercial mediante alianzas estratégicas entre investigadores y empresas.",
    cofinancing: "Financia hasta el 70% del costo del proyecto / 30% restante por los asociados",
    requirements: [
      "Alianza obligatoria con Instituciones académicas o centros de investigación",
      "Componente científico-tecnológico sustancial e innovador",
      "Compromiso de transferencia del software o tecnología al sector productivo"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: true,
    miltonAplica: "SÍ — Recomendable para desarrollos de software que requieran validación científica muy alta (ej. big data avanzado, robótica, IA de aprendizaje profundo).",
    tips: "Un camino valioso para Milton es acercarse a un centro de innovación universitario para actuar de co-ejecutor técnico.",
    url: "https://www.anid.cl",
    referenceUrlText: "anid.cl → Fondef IDeA",
    type: "financiamiento"
  },

  /* --- LICITACIONES Y COMPRAS PÚBLICAS (MERCADO PÚBLICO) --- */
  {
    id: "lic-providencia-2026",
    name: "Compra Ágil: Soporte Tecnológico y Servidores Providencia",
    entity: "Soporte Muni",
    amount: "$4.500.000 CLP (Contrato directo express)",
    amountNumber: 4500000,
    deadline: "31 de Mayo de 2026",
    deadlineISO: "2026-05-31",
    status: FundStatus.THREE_DAYS,
    urgency: "CRITICAL",
    category: "Compra Ágil",
    description: "Proceso de compra pública express por debajo de las 100 UTM para proveer servicios de mantenimiento informático preventivo y soporte de servidores locales para la Municipalidad de Providencia.",
    cofinancing: "Compra Directa Fiscal a 30 días contra facturación",
    requirements: [
      "Inscripción activa o básica en el portal ChileProveedores",
      "Cargar cotización digital en formato PDF en el portal oficial Mercado Público",
      "Firma electrónica simple para envío de cotizaciones directas"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: false,
    miltonAplica: "SÍ — Al ser una compra ágil de software y servicios, Milton puede adjudicarla como Persona Natural inscrita en ChileProveedores antes de constituir su SpA.",
    tips: "El envío de la cotización toma menos de 10 minutos. Es la manera más veloz de ganar reputación en Mercado Público hoy mismo.",
    url: "https://www.mercadopublico.cl",
    referenceUrlText: "mercadopublico.cl → ID: 3412-10-CA26",
    type: "licitacion",
    chileCode: "3412-10-CA26",
    organizer: "Municipalidad de Providencia"
  },
  {
    id: "lic-fonasa-2026",
    name: "Rediseño de Plataforma Web de Afiliados FONASA",
    entity: "FONASA",
    amount: "$35.000.000 CLP",
    amountNumber: 35000000,
    deadline: "05 de Junio de 2026",
    deadlineISO: "2026-06-05",
    status: FundStatus.OPEN,
    urgency: "HIGH",
    category: "Licitación Pública",
    description: "Convocatoria nacional para el rediseño de UI/UX y desarrollo del front-end de la nueva plataforma centralizada de afiliados de FONASA Chile, integrando Clave Única y APIs de consulta.",
    cofinancing: "Pago contra hitos entregables de software evaluados por comité estatal",
    requirements: [
      "Inscripción o pre-aprobación legal en ChileProveedores nacional",
      "Experiencia comprobable de desarrollo React con TypeScript",
      "Garantía de seriedad de la oferta (vale vista o póliza por $100.000 CLP)"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: true,
    miltonAplica: "SÍ — Pero requiere formalizar su SpA en los próximos días e inscribirse para poder presentar la oferta definitiva antes de junio.",
    tips: "Formar un consorcio de profesionales o apresurar el trámite de Tu Empresa En Un Día para ingresar la propuesta de manera legal como SpA.",
    url: "https://www.mercadopublico.cl",
    referenceUrlText: "mercadopublico.cl → ID: 5421-12-LE26",
    type: "licitacion",
    chileCode: "5421-12-LE26",
    organizer: "Fondo Nacional de Salud (FONASA)"
  },
  {
    id: "lic-sence-2026",
    name: "Sistema de Auditoría y Seguimiento E-Learning",
    entity: "SENCE",
    amount: "$78.000.000 CLP",
    amountNumber: 78000000,
    deadline: "12 de Junio de 2026",
    deadlineISO: "2026-06-12",
    status: FundStatus.UPCOMING,
    urgency: "HIGH",
    category: "Licitación Pública",
    description: "Provisión de software SaaS de control biométrico para la fiscalización en tiempo real de asistencia estudiantil en planes de e-learning subvencionados por el Sence.",
    cofinancing: "Licitación de Adjudicación Directa Ordinaria",
    requirements: [
      "Estar constituido como Sociedad de Responsabilidad Limitada o SpA",
      "Patente comercial habilitada para el rubro de ingeniería de sistemas informáticos",
      "Firma electrónica avanzada de representantes corporativos"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: true,
    miltonAplica: "NO DIRECTAMENTE — Requiere infraestructura robusta y empresa SpA formalizada con historial bancario previo para boletas de garantía.",
    tips: "Una excelente estrategia para el equipo de Milton de 3 personas es sub-licitar parte del servicio aliándose con un proveedor grande del Estado.",
    url: "https://www.mercadopublico.cl",
    referenceUrlText: "mercadopublico.cl → ID: 8271-45-LP26",
    type: "licitacion",
    chileCode: "8271-45-LP26",
    organizer: "Servicio Nacional de Capacitación y Empleo"
  },
  {
    id: "lic-chilecompra-2026",
    name: "Convenio Marco: Desarrollo de Portales y Consultoría de Software",
    entity: "ChileCompra",
    amount: "$120.000.000 CLP (Techo Operativo Multianual)",
    amountNumber: 120000000,
    deadline: "18 de Julio de 2026",
    deadlineISO: "2026-07-18",
    status: FundStatus.OPEN,
    urgency: "MEDIUM",
    category: "Convenio Marco",
    description: "Convocatoria para habilitar proveedores calificados en el catálogo nacional de servicios TI, democratizando las compras directas del Estado sin licitaciones largas.",
    cofinancing: "Tarifario adjudicado por perfiles técnicos de hora de ingeniería",
    requirements: [
      "Constitución o vigencia legal de sociedad chilena de más de 6 meses",
      "Boleta de fiel cumplimiento mercantil emitida por institución financiera chilena",
      "Equipo con certificaciones en desarrollo seguro (ISO/IEC 27001 o similar)"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: true,
    miltonAplica: "SÍ — Una meta clave para Milton una vez constituya la SpA. Estar en Convenio Marco permite ventas automáticas con municipios y ministerios.",
    tips: "Revisar las bases técnicas de acreditación hoy. Es un catálogo que abre solamente cada dos años para el rubro informático de Chile.",
    url: "https://www.mercadopublico.cl",
    referenceUrlText: "mercadopublico.cl → ID: 2234-99-CM26",
    type: "licitacion",
    chileCode: "2234-99-CM26",
    organizer: "Dirección de Compras Públicas (ChileCompra)"
  },

  /* --- HACKATONES Y RETOS DE INNOVACIÓN --- */
  {
    id: "hack-women-tech-2026",
    name: "Hackathon Nacional StarTech Mujeres en Tecnología",
    entity: "StarTech Mujeres",
    amount: "$15.000.000 CLP (Subsidio no reembolsable directo)",
    amountNumber: 15000000,
    deadline: "28 de Mayo de 2026 (Mañana)",
    deadlineISO: "2026-05-28",
    status: FundStatus.TOMORROW,
    urgency: "CRITICAL",
    category: "Hackathon",
    description: "Competencia de programación y diseño de negocios de 48 horas express para acelerar soluciones digitales con enfoque comunitario y social, organizada por Google e incubadoras chilenas.",
    cofinancing: "100% Subvención no reembolsable + $5.000 USD en créditos de nube Vertex AI",
    requirements: [
      "Equipo fundador de 2 a 4 personas chilenas o residentes",
      "Al menos una cofundadora titular con participación societaria mayoritaria de software",
      "Prototipo web funcional en React/TypeScript con demo disponible al domingo de cierre"
    ],
    eligibilityGenderRequired: true,
    eligibilitySalesRestricted: true,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Si Milton y sus 3 socios integran de co-fundadora titular a su aliada femenina en el software.",
    tips: "Al cerrar mañana, inscribir inmediatamente la composición de la idea. Es una vía expresa de financiamiento libre de burocracia estatal.",
    url: "https://www.google.cl",
    referenceUrlText: "startechmujeres.cl → Registro Hackathon",
    type: "hackaton",
    chileCode: "WOMEN-TECH-CL",
    organizer: "Corfo Mujeres & StarTech Chile"
  },
  {
    id: "hack-google-sence-2026",
    name: "Hackathon Nacional de IA Aplicada Sence",
    entity: "Sence Hack",
    amount: "$10.000.000 CLP (Premios pecuniarios y capacitación)",
    amountNumber: 10000000,
    deadline: "01 de Junio de 2026",
    deadlineISO: "2026-06-01",
    status: FundStatus.OPEN,
    urgency: "HIGH",
    category: "Hackathon",
    description: "Competencia de co-creación tecnológica para idear y prototipar herramientas basadas en Inteligencia Artificial Generativa que mejoren la orientación laboral y reclutamiento en Chile.",
    cofinancing: "Premios directos en efectivo transferidos de forma express sin rendiciones lentas",
    requirements: [
      "Participación de equipos de investigadores o desarrolladores senior",
      "Uso mandatorio de APIs del ecosistema Google Cloud / Gemini AI",
      "Licenciamiento de la solución bajo código abierto (Open Source)"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Excelente desafío de 3 días para validar la capacidad del software de Milton integrando Gemini API.",
    tips: "Desarrollar una propuesta centrada en resolver casos prácticos de reconversión laboral técnica en Santiago.",
    url: "https://sence.gob.cl",
    referenceUrlText: "sence.gob.cl → IA Hack 2026",
    type: "hackaton",
    chileCode: "HACK-IA-2026",
    organizer: "Sence & Google Cloud Chile"
  },
  {
    id: "hack-codelco-2026",
    name: "Reto de Innovación Abierta: Codelco Minería Verde SaaS",
    entity: "CODELCO",
    amount: "$25.000.000 CLP (Premio + Financiamiento de piloto)",
    amountNumber: 25000000,
    deadline: "10 de Junio de 2026",
    deadlineISO: "2026-06-10",
    status: FundStatus.UPCOMING,
    urgency: "HIGH",
    category: "Reto País",
    description: "Convocatoria industrial del principal productor de cobre del mundo. Busca software y analítica avanzada para el ahorro de consumo hídrico y optimización algorítmica de plantas.",
    cofinancing: "Financiación íntegra para pilotaje industrial de 3 meses en División El Teniente",
    requirements: [
      "Ser persona natural con título profesional o SpA del rubro TI",
      "Disponibilidad técnica para pruebas de campo semestrales",
      "Propuesta de arquitectura segura con APIs integradas"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: true,
    requiresSpA: false,
    miltonAplica: "SÍ — Siempre que el software de optimización se adapte a flujos hídricos o simulación de eficiencia de recursos.",
    tips: "Presentar un MVP enfocado en algoritmos inteligentes. Codelco no exige propiedad del software, sólo los derechos de piloto en su mina.",
    url: "https://www.codelco.com",
    referenceUrlText: "codelco.com → Innovación El Teniente",
    type: "hackaton",
    chileCode: "CODELCO-TECH",
    organizer: "Corporación Nacional del Cobre (CODELCO)"
  },
  {
    id: "hack-santiago-smart-2026",
    name: "Hackathon Ciudad Inteligente RM Santiago",
    entity: "Gore Santiago",
    amount: "$8.000.000 CLP",
    amountNumber: 8000000,
    deadline: "25 de Junio de 2026",
    deadlineISO: "2026-06-25",
    status: FundStatus.OPEN,
    urgency: "MEDIUM",
    category: "Desafío Urbano",
    description: "Desafío de innovación del Gobierno Regional para crear aplicaciones cívicas que coordinen de mejor forma el transporte de comunas periféricas en la Región Metropolitana.",
    cofinancing: "Subsidio de activación rápida para desarrollo social de software",
    requirements: [
      "Ingenieros de software o residentes en comunas de Santiago de Chile",
      "Propuesta de integración con datos abiertos del Ministerio de Transportes y Telecomunicaciones",
      "Crear prototipo visual móvil o web testeable"
    ],
    eligibilityGenderRequired: false,
    eligibilitySalesRestricted: false,
    SIIRequired: false,
    requiresSpA: false,
    miltonAplica: "SÍ — Milton de San Bernardo califica perfectamente por representar el contexto urbano periférico real de la capital.",
    tips: "Usar APIs de mapas públicas (OpenStreetMap, etc.) y enfocar la usabilidad en celulares de gama baja.",
    url: "https://www.gobiernosantiago.cl",
    referenceUrlText: "gobiernosantiago.cl → Innovación Urbana",
    type: "hackaton",
    chileCode: "SMART-SANTIAGO",
    organizer: "Gobierno Regional Metropolitano de Santiago"
  }
];

export const ROADMAP_STEPS: RoadmapStep[] = [
  {
    id: "step-1",
    timeframe: "ESTA_SEMANA",
    dateText: "HOY - 27 de Mayo 2026",
    title: "Postulación Express Capital Abeja",
    desc: "Si hay mujer empresaria/socia en tu equipo, presentarse HOY mismo en Sercotec.cl para realizar la postulación en línea. Cierra de forma inminente.",
    isUrgent: true,
    color: "from-red-500/30 to-red-600/10 border-red-500/50"
  },
  {
    id: "step-2",
    timeframe: "ESTA_SEMANA",
    dateText: "27-28 de Mayo 2026",
    title: "Redacción del Pitch y Formulario",
    desc: "Ingresar a Corfo.cl y activar el borrador de postulación del 'Semilla Inicia Región Metropolitana'. Detallar el problema de mercado, la solución TI, y el componente de alto potencial.",
    isUrgent: true,
    color: "from-orange-500/30 to-orange-600/10 border-orange-500/50"
  },
  {
    id: "step-3",
    timeframe: "ESTA_SEMANA",
    dateText: "29 de Mayo 2026 (17:00 Hrs)",
    title: "Envío CORFO Semilla Inicia RM",
    desc: "Revisión definitiva y firma digital del borrador. Enviar obligatoriamente antes de la hora límite para evitar saturación de servidores gubernamentales.",
    isUrgent: true,
    color: "from-red-500/40 to-red-500/10 border-red-500/80 shadow-[0_0_15px_rgba(239,68,68,0.25)]"
  },
  {
    id: "step-4",
    timeframe: "JUNIO_2026",
    dateText: "1 al 9 de Junio 2026",
    title: "Enviar Perfil Crea y Valida (I+D)",
    desc: "Redacción del formulario sintético de perfil para proyecto tecnológico aplicado con componente innovador de software.",
    isUrgent: false,
    color: "from-amber-500/20 to-amber-600/5 border-amber-500/30"
  },
  {
    id: "step-5",
    timeframe: "JUNIO_2026",
    dateText: "10 de Junio 2026",
    title: "Constitución Express de SpA",
    desc: "Formalizar la startup mediante el portal estatal Tu Empresa En Un Día (registros.cl) de forma 100% o costo marginal, asignando capital inicial desde $1 CLP.",
    isUrgent: false,
    color: "from-blue-500/20 to-blue-600/5 border-blue-500/30"
  },
  {
    id: "step-6",
    timeframe: "JUNIO_2026",
    dateText: "15 de Junio 2026",
    title: "Padrón del Estado & Proveedores",
    desc: "Asociar la SpA en ChileProveedores y activar visibilidad en Mercado Público para disputar licitaciones del rubro de consultoría digital o desarrollo de software.",
    isUrgent: false,
    color: "from-blue-500/20 to-blue-600/5 border-blue-500/30"
  },
  {
    id: "step-7",
    timeframe: "JULIO_AGOSTO_2026",
    dateText: "1 de Julio 2026",
    title: "Postulación Súmate a Innovar Sostenible",
    desc: "Si el modelo de negocio cuenta con un ángulo de monitoreo energético u optimización ambiental de software, postular al fondo de fomento ecológico de CORFO.",
    isUrgent: false,
    color: "from-emerald-500/20 to-emerald-600/5 border-emerald-500/30"
  },
  {
    id: "step-8",
    timeframe: "JULIO_AGOSTO_2026",
    dateText: "Julio 2026",
    title: "Primera Licitación Compra Ágil",
    desc: "Monitorear en Mercado Público compras ágiles menores a 100 UTM para adjudicar los primeros contratos estatales como consultor SpA de informática.",
    isUrgent: false,
    color: "from-yellow-500/20 to-yellow-600/5 border-yellow-500/30"
  },
  {
    id: "step-9",
    timeframe: "JULIO_AGOSTO_2026",
    dateText: "1 Jul - 5 Ago 2026",
    title: "AcademIA HackLab 2026",
    desc: "Participar de la convocatoria de Ciudad Emergente y Google para acelerar el uso de Inteligencia Artificial aplicada en sistemas urbanos y ecológicos.",
    isUrgent: false,
    color: "from-indigo-500/20 to-indigo-600/5 border-indigo-500/30"
  },
  {
    id: "step-10",
    timeframe: "NOVIEMBRE_2026",
    dateText: "Noviembre 2026",
    title: "Postulación Startup Chile BIG 12",
    desc: "Postular a la segunda gran ronda internacional en categorías Build ($15M CLP) para ideas o Ignite ($30M CLP) con el producto SaaS en validación inicial.",
    isUrgent: false,
    color: "from-violet-500/30 to-violet-600/5 border-violet-500/45"
  }
];

export const DOCUMENT_REQUIREMENTS: DocRequirement[] = [
  {
    id: "doc-rut",
    title: "Cédula de Identidad Vigente (RUT)",
    desc: "Cédula chilena del titular del proyecto. Clave Única activa de manera obligatoria.",
    isSpecialForkForSpA: false
  },
  {
    id: "doc-sii",
    title: "Iniciación de Actividades en el SII",
    desc: "Si postulas como personal natural, se tramita de forma inmediata y digital en 1 día hábil vía Sii.cl.",
    isSpecialForkForSpA: false
  },
  {
    id: "doc-pitch",
    title: "Descripción del Proyecto TI (Pitch 2 Pág.)",
    desc: "Formulación del Pain/Problem, la solución tecnológica, el diferencial comercial de SaaS/IA, y tamaño de mercado.",
    isSpecialForkForSpA: false
  },
  {
    id: "doc-equipo",
    title: "Resumen de Currículum e Integrantes",
    desc: "Datos, RUTs, porcentaje de participación futura, y antecedentes de experiencia TI del equipo de 2-3 personas.",
    isSpecialForkForSpA: false
  },
  {
    id: "doc-budget",
    title: "Presupuesto Simplificado de 6 Meses",
    desc: "Planificación de fondos para el costeo de hosting, desarrollo, licencias de IA, activos y publicidad.",
    isSpecialForkForSpA: false
  },
  {
    id: "doc-woman",
    title: "Cédula de la Socia Fundadora (Si aplica)",
    desc: "RUT y certificado de nacimiento/vigencia de la mujer que lidera para validar acceso a los fondos con enfoque de género.",
    isSpecialForkForSpA: false
  },
  {
    id: "doc-spa-const",
    title: "Constitución en portalregistros.cl",
    desc: "Firma digital y registro del acta de la SpA. Idealmente capital inicial desde $1 CLP para formalización rápida.",
    isSpecialForkForSpA: true
  },
  {
    id: "doc-chileprov",
    title: "Inscripción en ChileProveedores",
    desc: "Imprescindible para licitaciones públicas y compras ágiles nacionales en Mercado Público.",
    isSpecialForkForSpA: true
  },
  {
    id: "doc-cert-vigency",
    title: "Certificado de Vigencia de la Sociedad",
    desc: "Documento emitido por el Conservador o el Registro de Empresas y Sociedades que acredita legalidad actual.",
    isSpecialForkForSpA: true
  }
];

export const STRATEGIC_LINKS = [
  {
    id: "l1",
    title: "CORFO",
    desc: "Portal central de fomento productivo de Chile. Aquí se gestionan los fondos Semilla Inicia y Crea y Valida.",
    url: "https://www.corfo.cl",
    action: "Semilla Inicia RM 2026"
  },
  {
    id: "l2",
    title: "SERCOTEC",
    desc: "Servicio de Cooperación Técnica. Gestiona el Capital Abeja (cierra hoy 27-05) y Capital Semilla tradicional.",
    url: "https://www.sercotec.cl",
    action: "Capital Abeja Postular HOY"
  },
  {
    id: "l3",
    title: "Startup Chile",
    desc: "La aceleradora pública número 1 de Latinoamérica. Revisa bases para programas Build ($15M) e Ignite ($30M).",
    url: "https://www.startupchile.org",
    action: "Boletín Alertas Noviembre"
  },
  {
    id: "l4",
    title: "Tu Empresa En Un Día",
    desc: "Constituye tu Sociedad por Acciones (SpA) sin intermediarios legales costosos, de forma express.",
    url: "https://www.registrodeempresasysociedades.cl",
    action: "Crear SpA Express"
  },
  {
    id: "l5",
    title: "Mercado Público",
    desc: "Mercado estatal de transacciones de Chile. Acceso a miles de licitaciones públicas y compras ágiles.",
    url: "https://www.mercadopublico.cl",
    action: "Buscar Licitaciones TI"
  }
];
